# Site configuration
title: TIL

theme: minima

collections:
  GitHubPages:
    output: true
    permalink: /:collection/:name
    fontawesome: fab fa-github

  OpenGL:
    output: true
    permalink: /:collection/:name
    fontawesome: fal fa-cube fa-spin