# Site configuration
title: TIL

theme: minima

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

paginate_path: "/blog/page:num/"
paginate: 3

collections:
  CPlusPlus:
    name: "C++"
    output: true
    permalink: /:collection/:name
    icon: <i class="fas fa-brackets-curly p-1"></i>

  GameMaker:
    name: "GameMaker"
    output: true
    permalink: /:collection/:name
    icon: <i class="fas fa-joystick p-1"></i>

  GitHubPages:
    name: "GitHub Pages"
    output: true
    permalink: /:collection/:name
    icon: <i class="fab fa-github p-1"></i>

  Godot:
    name: "Godot"
    output: true
    permalink: /:collection/:name
    icon: <img src="/assets/godot/icon.svg" class="p-1" alt="Godot logo" width="40" height="40">
