# Site configuration
title: TIL

theme: minima

plugins:
  - jekyll-paginate
  - jekyll-feed

  
paginate_path: "/blog/page:num/"
paginate: 3

collections:
  GitHubPages:
    output: true
    permalink: /:collection/:name
    fontawesome: fab fa-github

  OpenGL:
    output: true
    permalink: /:collection/:name
    fontawesome: fal fa-cube fa-spin
